name: reverse
on: [push]
jobs:
    main-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: set up NodeJS
              uses: actions/setup-node@v2
              with: 
                node-version: 14.x
            - run: ls -a
            - run: npm install
            - run: npm run test
